[package]
name = "cfg-load"
version = "0.0.1"
edition = "2024"

[dependencies]
cfg-grammar = { version = "0.0.1", path = "../cfg-grammar/" }
cfg-sequence = { version = "0.0.1", path = "../cfg-sequence/" }
tiny-earley = { path = "../../tiny-earley", version = "0.1" }
elsa = { version = "1.11", features = ["indexmap"] }
log = "0.4"
